# All Travis builds are a redundancy against Jenkins failures, except that we also use
# this for running builds on PRs from forks, because we're OSS friendly. :)
language: node_js
matrix:
  fast_finish: false
cache:
  directories:
    # Cache only the folder with Cypress binary, other caching takes longer and saves
    # less time, therefore this is more efficient than caching all.
    - ~/.cache/Cypress
before_install:
  - sudo apt-get install -y libgconf-2-4
jobs:
  include:
    - stage: test
      if: type = push OR (pull_request AND fork = true)
      name: 'Unit Tests and Production CI Tests'
      install: npm ci
      addons:
        chrome: stable
      script:
        - npm run test
        - npm run build
        - npm prune --production
        - CYPRESS_SKIP_EU=true npm run test:ci
notifications:
  email: false
